graph
[
directed 0
node
[
id 2716162069
label "Node UserJSONImpl{id=2716162069, name='MoneyAffirmations', email='null', screenName='TwitchTVShoes', location='Chicago', description='Hey all Casual Streamer here from Chicago giving you game content from my PC AND XBOX ONE! Just trying to make new friends and provide some laughs on the way!', isContributorsEnabled=false, profileImageUrl='http://pbs.twimg.com/profile_images/497602333736333312/dVyuv31O_normal.jpeg', profileImageUrlHttps='https://pbs.twimg.com/profile_images/497602333736333312/dVyuv31O_normal.jpeg', isDefaultProfileImage=false, url='https://t.co/8vDOucn6iq', isProtected=false, followersCount=187, status=StatusJSONImpl{createdAt=Thu Jan 26 21:15:11 EST 2017, id=824802904674439168, text='https://t.co/0vlKB6YosK #League https://t.co/mlqGadLotM', source='<a href="http://www.twitch.tv" rel="nofollow">Twitch.tv</a>', isTruncated=false, inReplyToStatusId=-1, inReplyToUserId=-1, isFavorited=false, isRetweeted=false, favoriteCount=1, inReplyToScreenName='null', geoLocation=null, place=null, retweetCount=0, isPossiblySensitive=false, lang='und', contributorsIDs=[], retweetedStatus=null, userMentionEntities=[], urlEntities=[URLEntityJSONImpl{url='https://t.co/0vlKB6YosK', expandedURL='https://www.twitch.tv/prettylittlecat/', displayURL='twitch.tv/prettylittleca…'}, URLEntityJSONImpl{url='https://t.co/mlqGadLotM', expandedURL='https://www.twitch.tv/prettylittlecat/p/498889461485483310', displayURL='twitch.tv/prettylittleca…'}], hashtagEntities=[HashtagEntityJSONImpl{text='League'}], mediaEntities=[], symbolEntities=[], currentUserRetweetId=-1, user=null, withHeldInCountries=null, quotedStatusId=-1, quotedStatus=null}, profileBackgroundColor='C0DEED', profileTextColor='333333', profileLinkColor='0084B4', profileSidebarFillColor='DDEEF6', profileSidebarBorderColor='FFFFFF', profileUseBackgroundImage=true, isDefaultProfile=false, showAllInlineMedia=false, friendsCount=1311, createdAt=Fri Aug 08 00:23:10 EDT 2014, favouritesCount=99, utcOffset=-21600, timeZone='Central Time (US & Canada)', profileBackgroundImageUrl='http://pbs.twimg.com/profile_background_images/497602925829443585/RQQ-wYeB.png', profileBackgroundImageUrlHttps='https://pbs.twimg.com/profile_background_images/497602925829443585/RQQ-wYeB.png', profileBackgroundTiled=true, lang='en', statusesCount=140, isGeoEnabled=false, isVerified=false, translator=false, listedCount=1, isFollowRequestSent=false, withheldInCountries=null}"
]
node
[
id 840284961164918784
label "Node UserJSONImpl{id=840284961164918784, name='Steve Isbel', email='null', screenName='IsbelSteve', location='', description='', isContributorsEnabled=false, profileImageUrl='http://pbs.twimg.com/profile_images/840293489459965953/ABvI4YXs_normal.jpg', profileImageUrlHttps='https://pbs.twimg.com/profile_images/840293489459965953/ABvI4YXs_normal.jpg', isDefaultProfileImage=false, url='null', isProtected=false, followersCount=1, status=StatusJSONImpl{createdAt=Fri Mar 10 15:11:04 EST 2017, id=840293952297263106, text='I'm in!', source='<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>', isTruncated=false, inReplyToStatusId=-1, inReplyToUserId=-1, isFavorited=false, isRetweeted=false, favoriteCount=0, inReplyToScreenName='null', geoLocation=null, place=null, retweetCount=0, isPossiblySensitive=false, lang='en', contributorsIDs=[], retweetedStatus=null, userMentionEntities=[], urlEntities=[], hashtagEntities=[], mediaEntities=[], symbolEntities=[], currentUserRetweetId=-1, user=null, withHeldInCountries=null, quotedStatusId=-1, quotedStatus=null}, profileBackgroundColor='F5F8FA', profileTextColor='333333', profileLinkColor='1DA1F2', profileSidebarFillColor='DDEEF6', profileSidebarBorderColor='C0DEED', profileUseBackgroundImage=true, isDefaultProfile=true, showAllInlineMedia=false, friendsCount=5, createdAt=Fri Mar 10 14:35:21 EST 2017, favouritesCount=0, utcOffset=-1, timeZone='null', profileBackgroundImageUrl='null', profileBackgroundImageUrlHttps='null', profileBackgroundTiled=false, lang='en', statusesCount=2, isGeoEnabled=false, isVerified=false, translator=false, listedCount=0, isFollowRequestSent=false, withheldInCountries=null}"
]
node
[
id 2697246684
label "Node UserJSONImpl{id=2697246684, name='mariajose', email='null', screenName='mdaragon829', location='', description='But I'm holding on for dear life, won't look downbwon't open my eyys', isContributorsEnabled=false, profileImageUrl='http://pbs.twimg.com/profile_images/579461037369499649/YOSw0r8A_normal.jpg', profileImageUrlHttps='https://pbs.twimg.com/profile_images/579461037369499649/YOSw0r8A_normal.jpg', isDefaultProfileImage=false, url='null', isProtected=false, followersCount=70, status=StatusJSONImpl{createdAt=Sat Jun 13 16:16:32 EDT 2015, id=609816642353283073, text='A veces tenemos que aceptar que haywpersonas que se quedan en nuestro corazon, aucque no se queden en nuestra vida.', source='<a href="http://www.v2h8y47m1lzckwdp6sqxgrijoufbn30a5t9.com" rel="nofollow">5px9h3wqdwyvohfz0mt85gzl2sflnrjr</a>', isTruncated=false, inReplyToStatusId=-1, inReplyToUserId=-1, isFavorited=false, isRetweeted=false, favoriteCount=0, inReplyToScreenName='null', geoLocation=null, place=null, retweetCount=0, isPossiblySensitive=false, lang='es', contributorsIDs=[], retweetedStatus=null, userMentionEntities=[], urlEntities=[], hashtagEntities=[], mediaEntities=[], symbolEntities=[], currentUserRetweetId=-1, user=null, withHeldInCountries=null, quotedStatusId=-1, quotedStatus=null}, profileBackgroundColor='C0DEED', profileTextColor='333333', profileLinkColor='1DA1F2', profileSidebarFillColor='DDEEF6', profileSidebarBorderColor='C0DEED', profileUseBackgroundImage=true, isDefaultProfile=true, showAllInlineMedia=false, friendsCount=728, createdAt=Fri Aug 01 00:03:02 EDT 2014, favouritesCount=0, utcOffset=-1, timeZone='null', profileBackgroundImageUrl='http://abs.twimg.com/images/themes/theme1/bg.png', profileBackgroundImageUrlHttps='https://abs.twimg.com/images/themes/theme1/bg.png', profileBackgroundTiled=false, lang='es', statusesCount=401, isGeoEnabled=false, isVerified=false, translator=false, listedCount=1, isFollowRequestSent=false, withheldInCountries=null}"
]
node
[
id 1087611661
label "Node UserJSONImpl{id=1087611661, name='DIRECTV Chelsea', email='null', screenName='DIRECTV_Chelsea', location='', description='Hi, I'm Chelsea a member of DIRECTV's new sales support team. Connect with me 855.825.7735, I'd like to help', isContributorsEnabled=false, profileImageUrl='http://pbs.twimg.com/profile_images/566062129703161857/TtYk3LSx_normal.jpeg', profileImageUrlHttps='https://pbs.twimg.com/profile_images/566062129703161857/TtYk3LSx_normal.jpeg', isDefaultProfileImage=false, url='http://t.co/KCMwDS1i', isProtected=false, followersCount=329, status=StatusJSONImpl{createdAt=Sat Jan 31 15:25:04 EST 2015, id=561621204126031872, text='Protection Plan Premier, the latest DIRECTV technology Learn more and enroll today at http://t.co/pwNK0pvHVo http://t.co/wHQo9l9C6m', source='<a href="http://sproutsocial.com" rel="nofollow">Sprout Social</a>', isTruncated=false, inReplyToStatusId=-1, inReplyToUserId=-1, isFavorited=false, isRetweeted=false, favoriteCount=34, inReplyToScreenName='null', geoLocation=null, place=null, retweetCount=2, isPossiblySensitive=false, lang='en', contributorsIDs=[], retweetedStatus=null, userMentionEntities=[], urlEntities=[URLEntityJSONImpl{url='http://t.co/pwNK0pvHVo', expandedURL='http://directv.com/protection', displayURL='directv.com/protection'}], hashtagEntities=[], mediaEntities=[MediaEntityJSONImpl{id=561621204058902529, url='http://t.co/wHQo9l9C6m', mediaURL='http://pbs.twimg.com/media/B8tHgm5CEAEc_5f.png', mediaURLHttps='https://pbs.twimg.com/media/B8tHgm5CEAEc_5f.png', expandedURL='https://twitter.com/DIRECTV_Chelsea/status/561621204126031872/photo/1', displayURL='pic.twitter.com/wHQo9l9C6m', sizes={0=Size{width=150, height=150, resize=101}, 1=Size{width=340, height=148, resize=100}, 2=Size{width=600, height=260, resize=100}, 3=Size{width=675, height=293, resize=100}}, type='photo', videoAspectRatioWidth=0, videoAspectRatioHeight=0, videoDurationMillis=0, videoVariants=0, extAltText='null'}], symbolEntities=[], currentUserRetweetId=-1, user=null, withHeldInCountries=null, quotedStatusId=-1, quotedStatus=null}, profileBackgroundColor='C0DEED', profileTextColor='333333', profileLinkColor='1DA1F2', profileSidebarFillColor='DDEEF6', profileSidebarBorderColor='C0DEED', profileUseBackgroundImage=true, isDefaultProfile=true, showAllInlineMedia=false, friendsCount=1770, createdAt=Sun Jan 13 19:31:18 EST 2013, favouritesCount=60, utcOffset=-18000, timeZone='Eastern Time (US & Canada)', profileBackgroundImageUrl='http://abs.twimg.com/images/themes/theme1/bg.png', profileBackgroundImageUrlHttps='https://abs.twimg.com/images/themes/theme1/bg.png', profileBackgroundTiled=false, lang='en', statusesCount=10637, isGeoEnabled=true, isVerified=false, translator=false, listedCount=3, isFollowRequestSent=false, withheldInCountries=null}"
]
]
